# [[chains]]
#   account_prefix = "cosmos"
#   clock_drift = "5s"
#   fee_granter = ""
#   gas_adjustment = 0.1
#   grpc_addr = "http://127.0.0.1:9090"
#   id = "ibc-0"
#   key_name = "testkey"
#   max_gas = 2000000.0
#   rpc_addr = "http://127.0.0.1:26657"
#   rpc_timeout = "10s"
#   store_prefix = "ibc"
#   trusting_period = "14days"
#   websocket_addr = "ws://localhost:26657/websocket"

#   [chains.gas_price]
#     denom = "one"
#     price = 0.001

#   [chains.trust_threshold]
#     denominator = "3"
#     numerator = "1"

# [[chains]]
#   account_prefix = "cosmos"
#   clock_drift = "5s"
#   gas_adjustment = 0.1
#   grpc_addr = "http://127.0.0.1:9091"
#   id = "ibc-1"
#   key_name = "testkey"
#   max_gas = 2000000.0
#   rpc_addr = "http://127.0.0.1:26557"
#   rpc_timeout = "10s"
#   store_prefix = "ibc"
#   trusting_period = "14days"
#   websocket_addr = "ws://localhost:26557/websocket"

#   [chains.gas_price]
#     denom = "two"
#     price = 0.001

#   [chains.trust_threshold]
#     denominator = "3"
#     numerator = "2"

[global]
  log_level = "info"

# [mode] # Not needed for hermes clear packets

#   [mode.channels]
#     enabled = false

#   [mode.clients]
#     enabled = true
#     misbehaviour = true
#     refresh = true

#   [mode.connections]
#     enabled = false

#   [mode.packets]
#     clear_interval = 100.0
#     clear_on_start = true
#     enabled = true
#     tx_confirmation = true

# [rest]
#   enabled = true
#   host = "127.0.0.1"
#   port = 3000.0

# [telemetry]
#   enabled = true
#   host = "127.0.0.1"
#   port = 3001.0